name: Gopherbot Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout gopherbot/gh-pages
        uses: actions/checkout@v2
        with:
          repository: lnxjedi/gopherbot
          persist-credentials: false
          fetch-depth: 0
          path: gopherbot-doc
          ref: gh-pages

      - name: Setup mdBook
        # peaceris/actions-mdbook v1.1.14
        uses: peaceiris/actions-mdbook@4b5ef36b314c2599664ca107bb8c02412548d79d
        with:
          mdbook-version: 'latest'

      - name: Build
        run: |
          mv gopherbot-doc/.git ghpages.git
          mdbook build -d ../gopherbot-doc ./doc
          mv ghpages.git gopherbot-doc/.git

      - name: Commit and push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        run: |
          cd gopherbot-doc
          git config --local user.email "parsley@linuxjedi.org"
          git config --local user.name "David Parsley"
          git add -A
          git commit -m "Automated update" || exit 0
          git push https://parsley42:${GITHUB_TOKEN}@github.com/lnxjedi/gopherbot gh-pages
